"""Per-user morning-notification preferences.

The morning brief is generated by the nightly batch but DELIVERED at the user's
chosen local time by `notify_delivery.send_due_briefs`. This module is the
read/write surface for the `notification_prefs` row.
"""
from typing import Optional
from uuid import UUID

from .db import connect

# Earliest selectable time, in the user's LOCAL clock. The brief recaps the day
# that just ended at the 06:00 local boundary, and the rolling batch generates it
# at the top of that hour — so the earliest a fresh brief can be delivered is
# shortly after 06:00 local. The 06:30 floor leaves the hourly generation tick a
# margin to finish before delivery. (Keep this in lockstep with the mobile floor
# in mobile/lib/notificationPrefs.ts.)
MIN_HOUR = 6
MIN_MINUTE = 30


def _clamp_time(hour: int, minute: int) -> tuple[int, int]:
    hour = max(0, min(23, int(hour)))
    minute = max(0, min(59, int(minute)))
    if hour < MIN_HOUR or (hour == MIN_HOUR and minute < MIN_MINUTE):
        return MIN_HOUR, MIN_MINUTE
    return hour, minute


def get_user_tz(user_id: UUID) -> str:
    """The user's stored IANA timezone, or 'UTC' when unset. The single source
    of truth for converting timestamps into a user's local day-bucket."""
    with connect() as conn:
        row = conn.execute(
            "SELECT tz FROM notification_prefs WHERE user_id = %s",
            (str(user_id),),
        ).fetchone()
    return (row["tz"] if row and row["tz"] else "UTC")


def get_prefs(user_id: UUID) -> Optional[dict]:
    with connect() as conn:
        row = conn.execute(
            "SELECT enabled, hour, minute, tz, last_pushed_day "
            "FROM notification_prefs WHERE user_id = %s",
            (str(user_id),),
        ).fetchone()
    return dict(row) if row else None


def upsert_prefs(
    user_id: UUID,
    enabled: bool,
    hour: int,
    minute: int,
    tz: str,
) -> dict:
    hour, minute = _clamp_time(hour, minute)
    tz = (tz or "UTC").strip() or "UTC"
    with connect() as conn:
        row = conn.execute(
            """
            INSERT INTO notification_prefs (user_id, enabled, hour, minute, tz, updated_at)
            VALUES (%s, %s, %s, %s, %s, NOW())
            ON CONFLICT (user_id) DO UPDATE SET
                enabled = EXCLUDED.enabled,
                hour = EXCLUDED.hour,
                minute = EXCLUDED.minute,
                tz = EXCLUDED.tz,
                updated_at = NOW()
            RETURNING enabled, hour, minute, tz, last_pushed_day
            """,
            (str(user_id), enabled, hour, minute, tz),
        ).fetchone()
    return dict(row)


def mark_pushed(user_id: UUID, day: str) -> None:
    with connect() as conn:
        conn.execute(
            "UPDATE notification_prefs SET last_pushed_day = %s WHERE user_id = %s",
            (day, str(user_id)),
        )
