"""Per-user morning-notification preferences.

The morning brief is generated by the nightly batch but DELIVERED at the user's
chosen local time by `notify_delivery.send_due_briefs`. This module is the
read/write surface for the `notification_prefs` row.
"""
from typing import Optional
from uuid import UUID

from .db import connect

# Earliest selectable time. The brief is generated by the 06:00 UTC batch, so a
# push before then would carry a stale (or missing) reflection — surface this as
# a floor in the UI too.
MIN_HOUR = 6
MIN_MINUTE = 15


def _clamp_time(hour: int, minute: int) -> tuple[int, int]:
    hour = max(0, min(23, int(hour)))
    minute = max(0, min(59, int(minute)))
    if hour < MIN_HOUR or (hour == MIN_HOUR and minute < MIN_MINUTE):
        return MIN_HOUR, MIN_MINUTE
    return hour, minute


def get_prefs(user_id: UUID) -> Optional[dict]:
    with connect() as conn:
        row = conn.execute(
            "SELECT enabled, hour, minute, tz, last_pushed_day "
            "FROM notification_prefs WHERE user_id = %s",
            (str(user_id),),
        ).fetchone()
    return dict(row) if row else None


def upsert_prefs(
    user_id: UUID,
    enabled: bool,
    hour: int,
    minute: int,
    tz: str,
) -> dict:
    hour, minute = _clamp_time(hour, minute)
    tz = (tz or "UTC").strip() or "UTC"
    with connect() as conn:
        row = conn.execute(
            """
            INSERT INTO notification_prefs (user_id, enabled, hour, minute, tz, updated_at)
            VALUES (%s, %s, %s, %s, %s, NOW())
            ON CONFLICT (user_id) DO UPDATE SET
                enabled = EXCLUDED.enabled,
                hour = EXCLUDED.hour,
                minute = EXCLUDED.minute,
                tz = EXCLUDED.tz,
                updated_at = NOW()
            RETURNING enabled, hour, minute, tz, last_pushed_day
            """,
            (str(user_id), enabled, hour, minute, tz),
        ).fetchone()
    return dict(row)


def mark_pushed(user_id: UUID, day: str) -> None:
    with connect() as conn:
        conn.execute(
            "UPDATE notification_prefs SET last_pushed_day = %s WHERE user_id = %s",
            (day, str(user_id)),
        )
